//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace Character
{
	public class character
	{
		public character (){ /* Constructor */ }

		public static int track_objective = 0;
		public static int TRACK_OBJECTIVE
		{
			get { return track_objective; }
			set { track_objective = value; }
		}
		
		
		public static int health = 100;
		public static int HEALTH
		{
			get { return health; }
			set { health = value; }
		}

	}
}

