//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Mission
{
	public class mission
	{
		public mission (){}

		private static bool isMenu = false;
		public static bool ISMENU
		{ 
			get { return isMenu; }
			set { isMenu = value; }
		}

		private static bool isFail = false;
		public static bool ISFAIL
		{
			get { return isFail; }
			set { isFail = value;}
		}

		private static bool isPass = false;
		public static bool ISPASS
		{
			get { return isPass; }
			set { isPass = value;}
		}
		
		private static bool isLevelLoad = false;
		public static bool ISLEVELLOAD
		{
			get { return isLevelLoad; }
			set { isLevelLoad = value; }
		}

		private static int statePivot = 0;
		public static int STATEPIVOT
		{
			get { return statePivot; }
			set { statePivot = value; }
		}

		private static int levelPivot = 0;
		public static int LEVELPIVOT
		{
			get{ return levelPivot; }
			set{ levelPivot = value; }
		}


		private static string[] objectives_level01 = new string[] {
			"Set your helmet visor by pressing the \"V\" key.", 
			"Click on the glowing blue to open the hatch.", 
			"Go straight to the glowing blue & take a picture of Earth",
			"Click the blue dot to set the camera",
			"Return back to the capsule."
		};
		
		public static string[] OBJ_LEVEL01
		{
			get { return objectives_level01; }
			set { objectives_level01 = value;}
		}

		private static bool isObjDone = false;
		public static bool IS_OBJ_DONE
		{
			get { return isObjDone; }
			set { isObjDone = value; }
		}



	}
}

